version: '3.8'

services:
  bot:
    build: ./TavrBot/.
    restart: always
    volumes:
      - ./TavrBot/TelegrammBot/TgVideos:/app/TelegrammBot/TgVideos
      - ./TavrBot/TelegrammBot/DataBase:/app/TelegrammBot/DataBase
      - ./TavrBot/TelegrammBot/logs:/app/TelegrammBot/logs
      - ./TavrBot/TelegrammBot/Plication.session:/app/tavrik.session
    env_file:
      - ./TavrBot/.env
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
